import type { ColorDefinition } from "../domain/types";

export const PALETTE: ColorDefinition[] = [
  { id: "red", name: "レッド", hex: "#D77679", tint: "#F9EEEE" },
  { id: "vermilion", name: "朱色", hex: "#DE886C", tint: "#FBF0EB" },
  { id: "orange", name: "オレンジ", hex: "#E7A36D", tint: "#FBF2E9" },
  { id: "apricot", name: "アプリコット", hex: "#E5B18A", tint: "#FBF3ED" },
  { id: "marigold", name: "山吹", hex: "#DAB153", tint: "#FBF7E8" },
  { id: "yellow", name: "イエロー", hex: "#D9C965", tint: "#FAF9E8" },
  { id: "lime", name: "黄緑", hex: "#B7CA79", tint: "#F4F8E9" },
  { id: "grass", name: "若草", hex: "#A8C883", tint: "#F1F7E9" },
  { id: "pale-green", name: "ペールグリーン", hex: "#A9D8AE", tint: "#F0F8F1" },
  { id: "leaf", name: "リーフグリーン", hex: "#80BA87", tint: "#ECF6EE" },
  { id: "forest", name: "深緑", hex: "#689A80", tint: "#EAF3EF" },
  { id: "mint", name: "ミント", hex: "#91D6C1", tint: "#ECF8F4" },
  { id: "teal", name: "青緑", hex: "#71B9AF", tint: "#EAF5F3" },
  { id: "aqua", name: "アクア", hex: "#80CED5", tint: "#ECF8F8" },
  { id: "sky", name: "空色", hex: "#9ACBE5", tint: "#EFF7FA" },
  { id: "blue", name: "ブルー", hex: "#86B3DF", tint: "#EEF4FA" },
  { id: "indigo", name: "群青", hex: "#818FC9", tint: "#F0F1F8" },
  { id: "navy", name: "ネイビー", hex: "#788DAE", tint: "#EEF1F5" },
  { id: "violet", name: "バイオレット", hex: "#AB9ACC", tint: "#F3F0F8" },
  { id: "lavender", name: "ラベンダー", hex: "#C4ADE0", tint: "#F6F1FA" },
  { id: "lilac", name: "ライラック", hex: "#C9B5D5", tint: "#F7F2F8" },
  { id: "pink", name: "ピンク", hex: "#E8A9BD", tint: "#FCF0F4" },
  { id: "rose", name: "ローズ", hex: "#D98DA3", tint: "#FAEEF2" },
  { id: "coral", name: "コーラル", hex: "#E8A195", tint: "#FCF0ED" },
  { id: "peach", name: "ピーチ", hex: "#E9B9A5", tint: "#FCF4EF" },
  { id: "beige", name: "ベージュ", hex: "#CEB99A", tint: "#F8F4ED" },
  { id: "ochre", name: "黄土", hex: "#C8A16D", tint: "#F8F1E8" },
  { id: "brown", name: "ブラウン", hex: "#A88E7D", tint: "#F5F0EC" },
  { id: "slate", name: "スレート", hex: "#91A7AA", tint: "#EFF4F4" },
  { id: "gray", name: "グレー", hex: "#ABB1B1", tint: "#F3F5F4" },
  { id: "brick", name: "レンガ", hex: "#B96959", tint: "#FAEFEC" },
  { id: "terracotta", name: "テラコッタ", hex: "#CC8267", tint: "#FBF0EA" },
  { id: "rust", name: "赤茶", hex: "#B97550", tint: "#F9EFE8" },
  { id: "amber", name: "アンバー", hex: "#DCAD61", tint: "#FCF5E8" },
  { id: "honey", name: "ハニー", hex: "#DFC18A", tint: "#FCF7ED" },
  { id: "cream", name: "クリーム", hex: "#EEE2BE", tint: "#FCFAF2" },
  { id: "white", name: "ホワイト", hex: "#FFFFFF", tint: "#F8F8F7" },
  { id: "black", name: "ブラック", hex: "#242628", tint: "#F0F1F2" },
];
export const DEFAULT_COLOR = PALETTE[8];
export const colorById = (id?: string) =>
  PALETTE.find((color) => color.id === id) ?? DEFAULT_COLOR;
